### ISSUE TITLE
Amplify Gen2 Data Construct does not expose tables or cfnTables

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-category-api#2137]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20

### Amplify CLI Version

gen 2

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Based on https://docs.amplify.aws/gen2/build-a-backend/data/override-resources/ I should be able to access the tables the data construct creates, but those objects are empty

```
import { defineBackend } from '@aws-amplify/backend';
import { auth } from './auth/resource.js';
import { data } from './data/resource.js';

const backend = defineBackend({
  auth,
  data,
});

const dataResources = backend.resources.data.resources;

console.log(dataResources.tables); // {}
console.log(dataResources.cfnResources.cfnTables); // {}

Object.values(dataResources.cfnResources.cfnTables).forEach((table) => {
  console.log(table);
});
```

### Expected behavior

I should have access to them like the docs says

### Reproduction steps

Follow https://docs.amplify.aws/gen2/start/ to create a gen2 app, then write the code in https://docs.amplify.aws/gen2/build-a-backend/data/override-resources/ it will fail because `dataResources.tables["Todo"]` is undefined because the tables object is empty. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @dbanksdesign, Thank you for bringing this to our attention. We've managed to replicate the issue, so we're categorizing it as a bug for the team to investigate further.

<img width="1349" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/116acfc5-615f-4926-b1f6-fa606815f75c">

**Comment by palpatim** [comment]
The issue here is that the Data construct's table creation strategy is to use the Amplify-provisioned iterative tables, rather than the CloudFormation-managed default. That means the resource shows up under `dataResources.amplifyDynamoDbTables["Todo"]` rather than `dataResources.tables["Todo"]`. That object exposes a different set of properties than the Table, so to accomplish the example, you'd do:

```ts
Object.values(dataResources.amplifyDynamoDbTables).forEach((table) => {
  table.pointInTimeRecoveryEnabled = false;
});
```

@AaronZyLee will be working to find the right way to update our docs to reflect this change.

**Comment by bebbo-zz** [comment]
Would I be able to get an ARN or StreamARN via amplifyDynamoDbTables? If not, I assume it is more than just a documentation problem, right?

**Comment by marnutux** [comment]
I did a test directly with CDK, and I didn't encounter the problem (https://gist.github.com/marnutux/f22b06dc8398babfa1f04c61daf36b0b#file-amplify-stack-example-ts-L30). I only have the issue when using the abstraction `defineData`, so I'm not sure if it should be reported as an issue at https://github.com/aws-amplify/amplify-backend.

**Comment by jrobertshawe** [comment]
Hi there.  Via the same method, would I be able to add a Global Index.  I did not see a way to do this via the Data resource model

**Comment by AnilMaktala** [comment]
Hey, We are working on it and it will be released as part of GA.

**Comment by AnilMaktala** [comment]
Hey @jrobertshawe, We have completed the work for backend and currently working on the client side library. We will let you  know as soon as it is released.

**Comment by AnilMaktala** [comment]
This issue has been fixed in release:

@aws-amplify/backend": "^0.13.0-beta.6
@aws-amplify/backend-cli": "^0.12.0-beta.6

**Comment by pavinthan** [comment]
@AnilMaktala still same, here are my amplify backend versions 

```
@aws-amplify/backend": "^0.13.0-beta.17
@aws-amplify/backend-cli": "^0.12.0-beta.19
```

**Comment by renebrandel** [comment]
@pavinthan - you should be able to access the resources under `cfnResources.cfnAmplifyTables` the reason is we're exposing them via a custom CDK resource in order to allow for multiple GSI updates.

**Comment by dwil618** [comment]
Hi @renebrandel 

I have been following a trail of issues and discord threads all pointing to this issue. As far as I can tell the tables and cfnTables still don't work. Unless I am missing something?

I would like to be able to add a DynamoEventSource for my lambda as described in the [documentation](https://docs.amplify.aws/react/build-a-backend/functions/examples/dynamo-db-stream/)

Also looking at other challenges like adding Tags to my tables. Do you have any advice here?

**Comment by renebrandel** [comment]
Hey. You should be able to use cfnAmplifyTables, which provide the same interface. The reasons is to address some of the workflow problems (like updating multiple GSIs in a single request) requires us to use a custom Amplify DDB table resource.

**Comment by renebrandel** [comment]
The L2 reference (.tables) should work as is though.

**Comment by dwil618** [comment]
Thanks for the speedy response and clarification! First part was my misunderstanding of the different interfaces. 

I still have some problem with adding tags though. I see no error when using the below code, but it doesn't add any tags in the generated template/deployed resource.
`Tags.of(backend.data.resources.tables.Task).add('test', '123');`

**Comment by paulochagass** [comment]
> Thanks for the speedy response and clarification! First part was my misunderstanding of the different interfaces.
> 
> I still have some problem with adding tags though. I see no error when using the below code, but it doesn't add any tags in the generated template/deployed resource. `Tags.of(backend.data.resources.tables.Task).add('test', '123');`

Same problem here.

**Comment by MyNameIsTakenOMG** [comment]
Similar here, when I tried to override my GSI property like this:
```javascript
backend.data.resources.cfnResources.cfnTables['Todo'].addOverride(
  'Properties.GlobalSecondaryIndexes.0.Projection.ProjectionType',
  'INCLUDE'
);
```
, and it just threw me this error:
```javascript
TypeError: Cannot read properties of undefined (reading 'addOverride')
```
and in my case, the packages I am using: 
```javascript
    "@aws-amplify/backend": "^1.2.1",
    "@aws-amplify/backend-cli": "^1.2.6",
```
. So the workaround I could think of is to use custom resource. However, still I believe it would be better if we could override these properties like other resources

**Comment by MyNameIsTakenOMG** [comment]
Same here. And in my case, I was trying to override some settings for my gsi, but in the end I had to use custom resource to help me with that.

I understand the amplify devs have their reasons to design `backend.data` this way, but I hope in the near future we could have more flexibility to configure the underlying dynamodb table, for example, in my case, maybe we could have an option to configure GSIs for our tables through `backend.data.resources.cfnResources.amplifyDynamoDbTables`
