### ISSUE TITLE
Python 3.6 Runtime is deprecated // Cannot explicitly specify higher runtime 

### ISSUE THREAD

**Issue by andy-HM** [aws-amplify/amplify-category-api#715]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.3.0

### Amplify CLI Version

9.2.0

### What operating system are you using?

MacOS - Latest

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Amplify Categories

auth, storage, function, api, hosting, interactions, predictions

### Amplify Commands

push

### Describe the bug

I am adding the @searchable directive to my DynamoDB model and am receiving an error stating that the "Python3.6" runtime is deprecated when trying to create the "DdbToEsFn" function for passing data from DynamoDB to ElasticSearch.  This is the root problem I am trying to overcome.  This seems to be a duplicate issue of aws-amplify/amplify-cli#10242 and was supposed to be fixed by aws-amplify/amplify-cli#10243 but it does not appear to be resolved.

However, I am also unable to specify my desired runtime when pushing my changes.  I have tried editing the backend/api/stacks/customResources.json to explicitly define which runtime should be used for the creation of the function.  It does not appear this is being used since I still receive the Python3.6 error.

Here is how I am specifying in CustomResources.json:
`    "ElasticSearchStreamingLambdaRuntime": {
        "Type": "String",
        "Description": "The lambda runtime                 (https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime)",
        "Default": "python3.9"
    },
`

The questions I have are:

1. Why is the latest Amplify CLI using a deprecated Python runtime by default
2. What is the best way to customize deployments since CustomResources.json does not appear to be used and the documentation is not clear.

### Expected behavior

1. The current Amplify CLI should not use a deprecated runtime
2. I should be able to specify the runtime to use during the push command

### Reproduction steps

1. Add the @searchable directive to my table
2. run the CLI command: `amplify push -y`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

df818ff082e2c2b8b4ff4fa8e60d60ec

### Log output

<details>

```
# Put your logs below this line

CREATE_FAILED ElasticSearchStreamingLambdaFunction AWS::Lambda::Function Sat Aug 06 2022 09:06:34 GMT-0500 (Central Daylight Time) Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: c8ac347e-48cb-49c0-91fc-340f3fb751cd)" (RequestToken: 7d5e5d89-e5bc-bccc-effa-9d0697d3e506, HandlerErrorCode: InvalidRequest)

```

</details>

### Additional information

Thank you!

**Comment by ykethan** [comment]
Hey @andy-HM, Thank you for reaching out. From the project identifier provided I noticed that the AppSync API currently utilizes V1 transformer version. On further investigation I was able to find that for v1 transformer the lambda function migration from 3.6 to 3.9 is expected to be released in the upcoming CLI releases. 

Note: once a new CLI version with the fix has been released, I would adding a empty space in the schema then push which is expected to migrate the function. 
additionally, I would recommend migrating from v1 to v2 transformer version as this will provide the application with the latest features and updates. 

marking as bug

**Comment by andy-HM** [comment]
Hello @ykethan,  thank you for the response!  Do you know anticipated release time for the release that will include this change?  Are we talking days, weeks, months away?  Would upgrading to v2 transformer naturally take care of this?  

I have plans on migrating to v2 transformer in the near term but was hoping to get somethings completed prior.

**Comment by ykethan** [comment]
Hello @andy-HM, unfortunatly I don't have a timeline on the release date. But in the v2 transformer the support for python 3.9 version has been released. https://github.com/aws-amplify/amplify-category-api/blob/8011afa6e58aa48e4f1c3613eaf2d00d65eae9ef/packages/graphql-elasticsearch-transformer/src/resources.ts#L53

The team will update the issue or release notes https://github.com/aws-amplify/amplify-cli/blob/dev/packages/amplify-cli/CHANGELOG.md as soon as the fix has been released .

**Comment by Danish-karim** [comment]
@ykethan i have the same issue upgrading to v2 aslo throws the same error....also tried adding "OpenSearchStreamingLambdaRuntime": "python3.9" to api parameters.json file but still the same

**Comment by alharris-at** [comment]
We have triaged this issue as high priority and will be working to reproduce the various use-cases here and provide fixes, including documentation updates.

In the interim, for customers still on GraphQL transformer version 1 - you can explicitly set your lambda runtime version by navigating to the `amplify/backend/api/<YourApiName>/parameters.json` file, and adding a new record `"ElasticSearchStreamingLambdaRuntime": "python3.9"` to set a specific runtime.

I've just confirmed this in a new v1-enabled app.

My full and complete `parameters.json` file can be found below.

```json
{
  "AppSyncApiName": "newappv1search",
  "DynamoDBBillingMode": "PAY_PER_REQUEST",
  "DynamoDBEnableServerSideEncryption": false,
  "ElasticSearchStreamingLambdaRuntime": "python3.9"
}
```

@andy-HM - I agree with you that the documentation here was quite lacking, I had to do some exploratory testing to figure out the right way to set these parameters for v1, and have not yet worked it out for a v2 app.

@Danish-karim - Are you able to first upgrade the lambda runtime while still on v1, then after a successful deployment execute the v2 migration, unblocking yourself?

**Comment by andy-HM** [comment]
Thank you @alharris-at ! I will give this a try, appreciate the response.

**Comment by rewardle-jason** [comment]
@alharris-at I am a colleague of @Danish-karim and had a go at your suggestions.  My findings are as follows:
- Updating the parameters.json before v2 upgrade did work. The DdbToEsFn does get created with  Python 3.9
- Ran migration to v2, fixed the documented issues and tried to push but it failed with the Python 3.6 issue again.

Looking at the cloudformation files I noticed a renaming of the runtime property.  From ElasticSearchStreamingLambdaRuntime to OpenSearchStreamingLambdaRuntime.  As an idea I updated the parameters.json with the new property and attempted to push the change.

This failed unexpectedly as it is the same change that worked while the graphql was using v1.  The cloudformation has the property in the build folder:

 "OpenSearchStreamingLambdaRuntime": {
            "Type": "String",
            "Default": "python3.6",
            "Description": "The lambda runtime                 (https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime)"
        },

And the parameter file in the build folder also has the property:

{
    "AppSyncApiName": "hidden",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "DynamoDBEnableServerSideEncryption": false,
    "DynamoDBEnablePointInTimeRecovery": true,
    "OpenSearchStreamingLambdaRuntime": "python3.9",
    "AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "hidden",
            "Outputs.UserPoolId"
        ]
    },
    "S3DeploymentBucket": "hidden",
    "S3DeploymentRootKey": "hidden"
}

So it is unclear why this did not work.

node : v16.15.1
amplify: v7.6.25

**Comment by ykethan** [comment]
hey @rewardle-jason @Danish-karim, I observed that the CLI version being used is v7.6.25. On checking into the CLI release notes the change for the python version was released in CLI version 8.0.3 https://github.com/aws-amplify/amplify-cli/pull/10243 , https://github.com/aws-amplify/amplify-cli/releases/tag/v8.0.3. Could you please upgrade the CLI version and let us know if this mitigates the issue. 

cc @alharris-at

**Comment by ttolvane** [comment]
Our root stack did not roll back automatically after encountering this issue during a production push. We had to go to the ElasticSearchStreamingLambdaFunction and edit the execution env to python3.9, and manually roll back from the root stack options in CloudFormation. Then add the v1 intermediary fix as described above and push again.

**Comment by majirosstefan** [comment]
Same here! 

Stack is in UPDATE_ROLLBACK_FAILED state and can not be updated.

**Comment by AaronZyLee** [comment]
@rewardle-jason If you migrate to the v2 but still get `python3.6` in the CFN template, you can try `amplify api override` command for the lambda runtime. After you run the command, you are able to find `amplify/backend/api/${api_name}/override.ts` file. The following code snippet should override the parameter in the CFN.
```TypeScript
import { AmplifyApiGraphQlResourceStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyApiGraphQlResourceStackTemplate) {
  resources.opensearch.OpenSearchStreamingLambdaFunction.runtime = "python3.9";
}

```

**Comment by andy-HM** [comment]
> We have triaged this issue as high priority and will be working to reproduce the various use-cases here and provide fixes, including documentation updates.
> 
> 
> 
> In the interim, for customers still on GraphQL transformer version 1 - you can explicitly set your lambda runtime version by navigating to the `amplify/backend/api/<YourApiName>/parameters.json` file, and adding a new record `"ElasticSearchStreamingLambdaRuntime": "python3.9"` to set a specific runtime.
> 
> 
> 
> I've just confirmed this in a new v1-enabled app.
> 
> 
> 
> My full and complete `parameters.json` file can be found below.
> 
> 
> 
> ```json
> 
> {
> 
>   "AppSyncApiName": "newappv1search",
> 
>   "DynamoDBBillingMode": "PAY_PER_REQUEST",
> 
>   "DynamoDBEnableServerSideEncryption": false,
> 
>   "ElasticSearchStreamingLambdaRuntime": "python3.9"
> 
> }
> 
> ```
> 
> 
> 
> @andy-HM - I agree with you that the documentation here was quite lacking, I had to do some exploratory testing to figure out the right way to set these parameters for v1, and have not yet worked it out for a v2 app.
> 
> 
> 
> @Danish-karim - Are you able to first upgrade the lambda runtime while still on v1, then after a successful deployment execute the v2 migration, unblocking yourself?

Hey @alharris-at , I just wanted to confirm that this solved the issue for me. Thanks again!  I do need to get upgraded to transformer v2 but this helps with the immediate situation.
